# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vigenere.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 440)
        MainWindow.setMinimumSize(QtCore.QSize(800, 440))
        MainWindow.setMaximumSize(QtCore.QSize(800, 440))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 800, 65))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 210, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 250, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_PlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_PlainText.setGeometry(QtCore.QRect(160, 100, 611, 87))
        self.txt_PlainText.setObjectName("txt_PlainText")
        self.txt_CipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_CipherText.setGeometry(QtCore.QRect(160, 250, 611, 87))
        self.txt_CipherText.setObjectName("txt_CipherText")
        self.txt_Key = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Key.setGeometry(QtCore.QRect(160, 200, 611, 31))
        self.txt_Key.setObjectName("txt_Key")
        self.btn_Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Encrypt.setGeometry(QtCore.QRect(260, 350, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Encrypt.setFont(font)
        self.btn_Encrypt.setObjectName("btn_Encrypt")
        self.btn_Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Decrypt.setGeometry(QtCore.QRect(460, 350, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_Decrypt.setFont(font)
        self.btn_Decrypt.setObjectName("btn_Decrypt")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vigenère Cipher"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">VIGENERE<span style=\" font-size:16pt;\"> CIPHER<br/>Đào Hữu Tiến - 2280603213</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Plain Text"))
        self.label_3.setText(_translate("MainWindow", "Key"))
        self.label_4.setText(_translate("MainWindow", "Cipher Text"))
        self.btn_Encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_Decrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
